### ISSUE TITLE
ZAP reports can be automatically created as an HTML file.

### ISSUE THREAD

**Issue by ghost** [Jiab77/zap-friendly-report#1]
After completing any given attack(s) using zapproxy, the option exists to create a report in html directly from the tool itself.

Peace, brother.

Edit: markdown as well. I had a look at my last report.

**Comment by Jiab77** [comment]
Hi @mozdevcontrib , could you please provide me a sample report in HTML?
At the moment I have the report structure I can format / output it in any other asked format. Just let me know. :smile:
