### ISSUE TITLE
Create a github page to use this tool online

### ISSUE THREAD

**Issue by JavanXD** [Jiab77/zap-friendly-report#2]
Your website "https://jiab77.dyn.ch/zap-friendly-report/" is not online anymore. 

Luckily your tool is a simple index.html and does not require any backend. Therefore you can simple setup an [github page](https://pages.github.com/) for it. I would be happy to see a GitHub page for it.

**Comment by Jiab77** [comment]
Hi @JavanXD, I think you're right, the way the project is done does not required any backend so it should work as an github page. I'll create it in the next days.

Thanks a lot for your contribution to the project! :+1:

**Comment by Jiab77** [comment]
Page created :wink:
