### ISSUE TITLE
Missing details like URL, affected Parameters

### ISSUE THREAD

**Issue by JavanXD** [Jiab77/zap-friendly-report#3]
I miss details like URLs and parameters which are in the XML file. But they are not displayed in the HTML View. 

Attached a screenshot how it looks at the moment:
![grafik](https://user-images.githubusercontent.com/4342160/83659327-ab568000-a5c3-11ea-8dcf-df5442aa322a.png)

Details like URL and affected parameter are missing in the UI.

**Comment by Jiab77** [comment]
Hi @JavanXD, normally you should see a link in the __name__ column, but as I can see on your screenshot. Is it possible for you to share just the relevant parts from your `xml` report that are missing in the UI?

Feel free to send it by private mail if you prefer :wink:

**Comment by JavanXD** [comment]
What i feel is missing are the following fields: 
![grafik](https://user-images.githubusercontent.com/4342160/84294592-b2443c00-ab49-11ea-8b71-d6afbac72a78.png) 
This screenshot is taken from the attached HTML export.

I am attaching you the XML Version of this export. [HTML and XML Export from the same scan.zip](https://github.com/Jiab77/zap-friendly-report/files/4759987/HTML.and.XML.Export.from.the.same.scan.zip)

**Comment by Jiab77** [comment]
@JavanXD Thanks a lot, it will be very helpful!

**Comment by Jiab77** [comment]
@JavanXD I've pushed the changes from the `dev` branch, can you please check if you still missing information from your reports?

Normally it should be fixed with commit: https://github.com/Jiab77/zap-friendly-report/commit/acbcd09c914ac4745c87eb57049cc38bba307999

**Comment by Jiab77** [comment]
I confirm that the issue remains unfixed. I've spotted what was missing, there is an `instances` array which is not parsed.

**Comment by Jiab77** [comment]
The issue should be fixed now. I'm closing it.
